insert into VoterDetails (nid, pin, name, nameEn, gender,bloodGroup,
            dateOfBirth,fatherName,motherName,spouseName,perDivision,
            perDistrict,perRMO,perCityCorporationOrMunicipality,
                perMouzaOrMoholla,perVillageOrRoad,perUpazila,
                perUnionOrWard,perPostOffice,perPostalCode,
                perWardForUnionPorishod,perAdditionalMouzaOrMoholla,
                perAdditionalVillageOrRoad,perHomeOrHoldingNo,
                perRegion,photoUrl,prDivision,prDistrict,
                prRMO,prCityCorporationOrMunicipality,
                prMouzaOrMoholla,prVillageOrRoad,prUpazila,
                prUnionOrWard,prPostOffice,prPostalCode,
                prWardForUnionPorishod,prAdditionalMouzaOrMoholla,
                prAdditionalVillageOrRoad,prHomeOrHoldingNo,
                prRegion,formNumber,voterArea,voterAreaCode,
                voterNumber,birthPlace,education,photo)
select nid, pin, name, nameEn, gender,bloodGroup,
            dateOfBirth,fatherName,motherName,spouseName,perDivision,perDistrict,perRMO,perCityCorporationOrMunicipality,
                perMouzaOrMoholla,perVillageOrRoad,perUpazila,
                perUnionOrWard,perPostOffice,perPostalCode,
                perWardForUnionPorishod,perAdditionalMouzaOrMoholla,
                perAdditionalVillageOrRoad,perHomeOrHoldingNo,
                perRegion,photoUrl,prDivision,prDistrict,
                prRMO,prCityCorporationOrMunicipality,
                prMouzaOrMoholla,prVillageOrRoad,prUpazila,
                prUnionOrWard,prPostOffice,prPostalCode,
                prWardForUnionPorishod,prAdditionalMouzaOrMoholla,
                prAdditionalVillageOrRoad,prHomeOrHoldingNo,
                prRegion,formNumber,voterArea,voterAreaCode,
                voterNumber,birthPlace,education,photo
from VoterDetails;
                
